platform :ios, “7.0”

use_frameworks!
target ‘MyCocoaPodPro’ do
pod 'JSONModel', '~> 1.2.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'YYKit', '~> 1.0.6'
pod 'OpenShare', '~> 0.0.1'
pod 'UMengAnalytics', '~> 4.0.2'
pod 'BaiduMapKit', '~> 2.10.2'
pod 'CocoaLumberjack', '~> 2.3.0'
pod 'SDWebImage', '~> 3.7.6’
pod 'pop', '~> 1.0.9'
pod 'AFNetworking', '~> 3.1.0'
pod 'ReactiveCocoa'
end